collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9768044
  lightness: 0.823194
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#4B4B4B'
    - '#888888'
    - '#BDBDBD'
  rhythmicContrast: 0.2566589
typography_spectrum: 0.2689713
layout_spectrum: 0.5615414
name: ayatake
