layout_spectrum: 0.5615414
color:
  saturation: 0.9768044
  lightness: 0.823194
  brandStrength: 0.6808216
  rhythmicContrast: 0.2566589
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.2689713
name: ayatake
